version: '3.3'
services:
  graphdb:
    build:
      context: /Users/andreykhalov/HULK/CroddFi/EXE/exe_prototype
      dockerfile: graphdb/Dockerfile
    container_name: graphdb_exe
    ports:
      - "7200:7200"
      - "7300:7300"
    volumes:
      - ./data:/opt/graphdb/home/data
    env_file:
      - ../.env