version: '3.3'

services:
  graphdb:
    image: ontotext/graphdb:latest
    container_name: graphdb_exe
    ports:
      - "7300:7300"
    volumes:
      - ./data:/opt/graphdb/home/data
    environment:

      # add correct credentials in .env.
      - GDB_ADMIN_USER=${GDB_ADMIN_USER}
      - GDB_ADMIN_PASSWORD=${GDB_ADMIN_PASSWORD}
